### ISSUE TITLE
driver test needs --ip defined not --ip-address

### ISSUE THREAD

**Issue by Limb** [gjr80/weewx-gw1000#11]
The README.md states "Note: If necessary you can specify the GW1000 IP address and port using the --ip-address and --port command line options. Refer to the GW1000 driver help using --help for further information."

However the driver actually expects --ip to be defined, and throws an error if --ip-address is used. (The --help command informs you to use --ip)

I would suggest changing the --ip parameter to --ip_address to be consistent with the weewx configuration file, which uses ip_address.

**Comment by gjr80** [comment]
Thanks for the feedback, it was a deliberate decision to use `--ip` but I can see it could be confusing. Will fix in b10.

**Comment by gjr80** [comment]
Commit 88987259a0ab8cedd2f17cfd496d779337a42796 refers
