### ISSUE TITLE
b12 Lost GW1000, Took WeeWX Down

### ISSUE THREAD

**Issue by gary-hammer** [gjr80/weewx-gw1000#16]
Running b12 with WeeWX 4.1.1 under python3, setup.py method.
This is the GW1000 stanza in weewx.conf:
`# Options for extension 'GW1000'
[GW1000]
    driver = user.gw1000
    ip_address = 10.10.100.125
    port = 45000
    poll_interval = 16
    [[field_map_extensions]]
        supplyVoltage = wh40_batt
        windBatteryStatus = wh68_batt
        txBatteryStatus = wh26_batt`

On my test machine, I noticed this morning that there was no live data.
systemctl status weewx shows:
`● weewx.service - weewx weather system
     Loaded: loaded (/etc/systemd/system/weewx.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2020-09-09 17:36:50 EDT; 15h ago
    Process: 174609 ExecStart=/home/weewx/bin/weewxd --daemon --pidfile=/var/run/weewx.pid /home/weewx/weewx.conf (code=exited, status=0/SUCCESS)
   Main PID: 174624 (code=exited, status=4)

Sep 09 17:36:50 tester weewxd[174624]: weewx[174624] CRITICAL weewx.engine:     ****      self.mac = self.get_mac_address()
Sep 09 17:36:50 tester weewxd[174624]: weewx[174624] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 2407, in get_mac_ad>
Sep 09 17:36:50 tester weewxd[174624]: weewx[174624] CRITICAL weewx.engine:     ****      return self.send_cmd_with_retries('CMD_READ_STATION_MAC')
Sep 09 17:36:50 tester weewxd[174624]: weewx[174624] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 2532, in send_cmd_w>
Sep 09 17:36:50 tester weewxd[174624]: weewx[174624] CRITICAL weewx.engine:     ****      raise GW1000IOError(_msg)
Sep 09 17:36:50 tester weewxd[174624]: weewx[174624] CRITICAL weewx.engine:     ****  user.gw1000.GW1000IOError: Failed to obtain response to command '>
Sep 09 17:36:50 tester weewxd[174624]: weewx[174624] CRITICAL __main__: Unable to load driver: Failed to obtain response to command 'CMD_READ_STATION_M>
Sep 09 17:36:50 tester weewxd[174624]: weewx[174624] CRITICAL __main__:     ****  Exiting...
Sep 09 17:36:50 tester systemd[1]: weewx.service: Main process exited, code=exited, status=4/NOPERMISSION
Sep 09 17:36:50 tester systemd[1]: weewx.service: Failed with result 'exit-code'.
`
A restart of weewx has things working fine again.

Because I have my 'production' weewx online and CumulusMX on the test server, I can say that the network had no difficulty as both use the GW1000 and both have good data for yesterday and today.

Perhaps one of them stepped on the other, two calling for data at the same time?

**Comment by gjr80** [comment]
Not good. The portion of the stack trace your posted indicates the driver was loading so unless this was a startup (which I get the feeling it wasn't) it was trying to recover from something. Can you get me an extract from the log showing more of the leadup, would like to see the whole stack trace from the beginning and a little of what was going on before the stack trace so I can understand what the driver was doing in the leadup. Thanks.

**Comment by gary-hammer** [comment]
Here's what I have, I was not running debug level logs.

`Sep  9 17:30:17 tester weewx[174624] INFO weewx.manager: Added record 2020-09-09 17:30:00 EDT (1599687000) to database 'weewx.sdb'
Sep  9 17:30:17 tester weewx[174624] INFO weewx.manager: Added record 2020-09-09 17:30:00 EDT (1599687000) to daily summary in 'weewx.sdb'
Sep  9 17:30:18 tester weewx[174624] INFO weewx.cheetahgenerator: Generated 8 files for report SeasonsReport in 0.45 seconds
Sep  9 17:30:18 tester weewx[174624] INFO weewx.imagegenerator: Generated 15 images for report SeasonsReport in 0.29 seconds
Sep  9 17:30:18 tester weewx[174624] INFO weewx.reportengine: Copied 0 files to /var/www/html
Sep  9 17:30:18 tester weewx[174624] INFO weewx.cheetahgenerator: Generated 2 files for report Weather34Report in 0.08 seconds
Sep  9 17:30:18 tester weewx[174624] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/weather34/
Sep  9 17:30:18 tester weewx[174624] INFO weewx.cheetahgenerator: Generated 7 files for report w34Highcharts in 0.05 seconds
Sep  9 17:30:18 tester weewx[174624] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/weather34/w34highcharts
Sep  9 17:35:00 tester systemd[1]: Started Session 2310 of user root.
Sep  9 17:35:00 tester systemd[1]: session-2310.scope: Succeeded.
Sep  9 17:35:23 tester weewx[174624] ERROR user.gw1000: Failed to obtain response to command 'CMD_GW1000_LIVEDATA' after 3 attempts
Sep  9 17:35:23 tester weewx[174624] ERROR user.gw1000: Unable to obtain live sensor data
Sep  9 17:35:23 tester weewx[174624] INFO weewx.engine: Main loop exiting. Shutting engine down.
Sep  9 17:35:23 tester weewx[174624] INFO weewx.engine: Shutting down StdReport thread
Sep  9 17:35:24 tester weewx[174624] INFO user.gw1000: Gw1000Collector thread has been terminated
Sep  9 17:35:24 tester weewx[174624] CRITICAL __main__: Caught WeeWxIOError: Failed to obtain response to command 'CMD_GW1000_LIVEDATA' after 3 attempts
Sep  9 17:35:24 tester weewx[174624] CRITICAL __main__:     ****  Waiting 60 seconds then retrying...
Sep  9 17:36:24 tester weewx[174624] INFO __main__: retrying...
Sep  9 17:36:24 tester weewx[174624] INFO __main__: Using configuration file /home/weewx/weewx.conf
Sep  9 17:36:24 tester weewx[174624] INFO __main__: Debug is 0
Sep  9 17:36:24 tester weewx[174624] INFO weewx.engine: Loading station type GW1000 (user.gw1000)
Sep  9 17:36:50 tester weewx[174624] ERROR user.gw1000: Failed to obtain response to command 'CMD_READ_STATION_MAC' after 3 attempts
Sep  9 17:36:50 tester weewx[174624] ERROR weewx.engine: Import of driver failed: Failed to obtain response to command 'CMD_READ_STATION_MAC' after 3 attempts (<class 'user.gw1000.GW1000IOError'>)
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****  Traceback (most recent call last):
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/weewx/engine.py", line 103, in setupStation
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****      self.console = loader_function(config_dict, self)
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 1293, in loader
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****      return Gw1000Driver(**config_dict[DRIVER_NAME])
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 1568, in __init__
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****      super(Gw1000Driver, self).__init__(**stn_dict)
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 757, in __init__
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****      self.collector = Gw1000Collector(ip_address=self.ip_address,
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 1863, in __init__
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****      self.station = Gw1000Collector.Station(ip_address=ip_address,
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 2276, in __init__
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****      self.mac = self.get_mac_address()
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 2407, in get_mac_address
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****      return self.send_cmd_with_retries('CMD_READ_STATION_MAC')
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 2532, in send_cmd_with_retries
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****      raise GW1000IOError(_msg)
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****  user.gw1000.GW1000IOError: Failed to obtain response to command 'CMD_READ_STATION_MAC' after 3 attempts
Sep  9 17:36:50 tester weewx[174624] CRITICAL __main__: Unable to load driver: Failed to obtain response to command 'CMD_READ_STATION_MAC' after 3 attempts
Sep  9 17:36:50 tester weewx[174624] CRITICAL __main__:     ****  Exiting...
Sep  9 17:36:50 tester systemd[1]: weewx.service: Main process exited, code=exited, status=4/NOPERMISSION`

**Comment by gary-hammer** [comment]
Here what I have, no debug logs though.

`Sep  9 17:30:17 tester weewx[174624] INFO weewx.manager: Added record 2020-09-09 17:30:00 EDT (1599687000) to database 'weewx.sdb'
Sep  9 17:30:17 tester weewx[174624] INFO weewx.manager: Added record 2020-09-09 17:30:00 EDT (1599687000) to daily summary in 'weewx.sdb'
Sep  9 17:30:18 tester weewx[174624] INFO weewx.cheetahgenerator: Generated 8 files for report SeasonsReport in 0.45 seconds
Sep  9 17:30:18 tester weewx[174624] INFO weewx.imagegenerator: Generated 15 images for report SeasonsReport in 0.29 seconds
Sep  9 17:30:18 tester weewx[174624] INFO weewx.reportengine: Copied 0 files to /var/www/html
Sep  9 17:30:18 tester weewx[174624] INFO weewx.cheetahgenerator: Generated 2 files for report Weather34Report in 0.08 seconds
Sep  9 17:30:18 tester weewx[174624] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/weather34/
Sep  9 17:30:18 tester weewx[174624] INFO weewx.cheetahgenerator: Generated 7 files for report w34Highcharts in 0.05 seconds
Sep  9 17:30:18 tester weewx[174624] INFO weewx.reportengine: Copied 0 files to /var/www/html/weewx/weather34/w34highcharts
Sep  9 17:35:23 tester weewx[174624] ERROR user.gw1000: Failed to obtain response to command 'CMD_GW1000_LIVEDATA' after 3 attempts
Sep  9 17:35:23 tester weewx[174624] ERROR user.gw1000: Unable to obtain live sensor data
Sep  9 17:35:23 tester weewx[174624] INFO weewx.engine: Main loop exiting. Shutting engine down.
Sep  9 17:35:23 tester weewx[174624] INFO weewx.engine: Shutting down StdReport thread
Sep  9 17:35:24 tester weewx[174624] INFO user.gw1000: Gw1000Collector thread has been terminated
Sep  9 17:35:24 tester weewx[174624] CRITICAL __main__: Caught WeeWxIOError: Failed to obtain response to command 'CMD_GW1000_LIVEDATA' after 3 attempts
Sep  9 17:35:24 tester weewx[174624] CRITICAL __main__:     ****  Waiting 60 seconds then retrying...
Sep  9 17:36:24 tester weewx[174624] INFO __main__: retrying...
Sep  9 17:36:24 tester weewx[174624] INFO __main__: Using configuration file /home/weewx/weewx.conf
Sep  9 17:36:24 tester weewx[174624] INFO __main__: Debug is 0
Sep  9 17:36:24 tester weewx[174624] INFO weewx.engine: Loading station type GW1000 (user.gw1000)
Sep  9 17:36:50 tester weewx[174624] ERROR user.gw1000: Failed to obtain response to command 'CMD_READ_STATION_MAC' after 3 attempts
Sep  9 17:36:50 tester weewx[174624] ERROR weewx.engine: Import of driver failed: Failed to obtain response to command 'CMD_READ_STATION_MAC' after 3 attempts (<class 'user.gw1000.GW1000IOError'>)
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****  Traceback (most recent call last):
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/weewx/engine.py", line 103, in setupStation
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****      self.console = loader_function(config_dict, self)
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 1293, in loader
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****      return Gw1000Driver(**config_dict[DRIVER_NAME])
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 1568, in __init__
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****      super(Gw1000Driver, self).__init__(**stn_dict)
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 757, in __init__
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****      self.collector = Gw1000Collector(ip_address=self.ip_address,
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 1863, in __init__
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****      self.station = Gw1000Collector.Station(ip_address=ip_address,
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 2276, in __init__
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****      self.mac = self.get_mac_address()
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 2407, in get_mac_address
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****      return self.send_cmd_with_retries('CMD_READ_STATION_MAC')
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 2532, in send_cmd_with_retries
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****      raise GW1000IOError(_msg)
Sep  9 17:36:50 tester weewx[174624] CRITICAL weewx.engine:     ****  user.gw1000.GW1000IOError: Failed to obtain response to command 'CMD_READ_STATION_MAC' after 3 attempts
Sep  9 17:36:50 tester weewx[174624] CRITICAL __main__: Unable to load driver: Failed to obtain response to command 'CMD_READ_STATION_MAC' after 3 attempts
Sep  9 17:36:50 tester weewx[174624] CRITICAL __main__:     ****  Exiting...
Sep  9 17:36:50 tester systemd[1]: weewx.service: Main process exited, code=exited, status=4/NOPERMISSION
Sep  9 17:36:50 tester systemd[1]: weewx.service: Failed with result 'exit-code'.`

**Comment by gjr80** [comment]
OK, thanks. So there was an earlier failure to get data from the GW1000 that caused a shutdown. I’ll work through the code again to see if it behaved as intended. The MAC is obtained at driver startup so that if subsequent contact is lost the driver can use the MAC to make sure it reconnects to the correct device. If the driver fails to get the MAC it appears that is causing a hard exit when it really should just trigger WeeWX to restart the driver. This won’t fix the initial cause of the lost contact but it will prevent WeeWX exiting.

Having a debug log may give us the reason for the initial failure though the cause of the failure does not affect the restart process that needs to be followed. If it’s a test machine and you can do it running with debug=1 might be helpful if there are any further similar failures.

**Comment by gary-hammer** [comment]
In my case, I have defined the IP address,  so that ought to guarantee the
driver is talking to the device it wants. Maybe if the IP is provided, skip
getting the MAC address.

I will run with debug for the weekend. I've changed the polling interval by
one second, just to try and avoid the production WeeWX polling.

It could have been that the production was active while the test was asking
for data. Don't know how quickly the GW1000 responds, if it needs a
recovery time, etc.

The good news is that the production machine hasn't seen any problems.

Gary

**Comment by gjr80** [comment]
> In my case, I have defined the IP address, so that ought to guarantee the driver is talking to the device it wants. Maybe if the IP is provided, skip getting the MAC address. 

Yes, that may well be what I do, or just swallow the error and deal with the consequences later if they arise. There are a shed load of moving parts; discovered IP/specified IP, service/driver etc are the two key ones but by the time you add in discovered port/specified port, the possibilities of multiple GW1000s etc the logic starts to get pretty complex.

> I will run with debug for the weekend. I've changed the polling interval by one second, just to try and avoid the production WeeWX polling. It could have been that the production was active while the test was asking for data. Don't know how quickly the GW1000 responds, if it needs a recovery time, etc. The good news is that the production machine hasn't seen any problems.

OK. The thing is polling the GW1000 should be pretty tolerant of the GW1000 being busy, any API request is retried three times 10 seconds apart (default values but can be changed). I guess the holes in the cheese could all line up, but three times 10 seconds apart? Would have been interesting to see what would have happened if the driver logic was correct and continuous retries attempted after 60 seconds. Having the holes line up I can understand but to have it happen again in 60 seconds would be more than co-incidence.

Out of interest what version is your production running, b11 or b12?

**Comment by gary-hammer** [comment]
Both are running b12.

Yes, it seemed pretty unlikely for the polling to coincide.

I see your point about the configuration. Best to make it resilient.

**Comment by gary-hammer** [comment]
Well, ran for days without a failure. I even took the network connection to my test machine down for 15 minutes yesterday and weewx kept chugging along.

Closing this issue now.
