### ISSUE TITLE
Battery Data Not Captured

### ISSUE THREAD

**Issue by gary-hammer** [gjr80/weewx-gw1000#2]
I have installed b5 into my WeeWX 4.1.1 Python 3 instance.
Works well, but I have one question and one observation.

My question is, how to configure the polling interval in weewx.conf
I used that to run directly and it works well for my sensors reporting intervals.

My observation is that battery data is not captured.
Using Interceptor, these are my extensions to the sensor map:
`    device_type = fineoffset-bridge
    port = 8000
    [[sensor_map_extensions]]
        windBatteryStatus = wh68_battery
        txBatteryStatus = wh26_battery
        supplyVoltage = wh40_battery`

Happy to see this driver.

**Comment by gjr80** [comment]
The polling interval can be set using the `poll_interval` config option under `[GW1000]` in `weewx.conf`. I have quickly documented the available config options [here](https://github.com/gjr80/weewx-gw1000/wiki/User's-Guide) in the driver wiki.

Battery status is a bit of a moving feast, to be truthful I thought I had them coming through in the loop packets (they are on my test system for some reason). I believe I have most of the simple individual sensor battery states working OK but some are not and I suspect the more complex sensor suites are not. I am working my way through the API documentation but will likely ask for some debug info from users with sensors/sensor suites that I do not have (I only have GW1000, WH31, WH32, WH41, WH51 and WH57, ie nothing that measures wind and rain). Stand by.
