### ISSUE TITLE
Indoor sensor change with outdoor sensor 

### ISSUE THREAD

**Issue by danitus13** [gjr80/weewx-gw1000#51]
I bought a waldbeck halley 6 in 1 with an additional indoor temperature sensor (clone hp1000 from froggit - - gw1000 ecowitt)
I installed weewx and used the your driver 
I want the indoor sensor which should be a Wh32, as the main outdoor sensor, what to change in weewx?

**Comment by gjr80** [comment]
There are two solutions; firstly you can re-map the respective WeeWX fields in `weewx.conf` under `[[StdCalibrate]]`. The second and preferred approach is to re-map the respective fields in the GW1000 driver. Unless you have specific requirements for the the WH32 data to appear in both `inTemp` and `outTemp` the preferred approach is the latter, ie to re-map the fields in the GW1000 driver.

To do this edit `weewx.conf`, locate the `[GW1000]` stanza and add a `[[field_map_extensions]]` stanza as follows:
```
[GW1000]
    ....
    [[[field_map_extensions]]
        outTemp = intemp
```        
Save `weewx.conf` and restart the WeeWX. Confirm that the correct data is appearing in WeeWX field `outTemp`.

**Note.** The above assumes that once your WH32 clone/equivalent sensor is connected to your station, data from the sensor appears in WeeWX field `inTemp`. If the data appears in another field the above mapping will need to be changed.

I prefer to keep this issue list for bugs in the GW1000 driver not for general support/configuration questions. As per the [GW1000 driver readme](https://github.com/gjr80/weewx-gw1000/blob/master/README.md#support) please post future general support question to the Google Groups [weewx-user forum](https://groups.google.com/g/weewx-user "Google Groups weewx-user forum").
