### ISSUE TITLE
Error when attempting to test the driver

### ISSUE THREAD

**Issue by Rayvenhaus** [gjr80/weewx-gw1000#54]
When issuing the following command from the command line:
sudo PYTHONPATH=/home/weewx/bin/weewx python3 -m user.gw1000 --test-driver

the following error is received:
/usr/bin/python3: Error while finding module specification for 'user.gw1000' (ModuleNotFoundError: No module named 'user')

Although the driver is installed and appears to be working just fine with WeeWX

System: Raspberry PI 4B
OS: Raspberry OS Bullseye

**Comment by gjr80** [comment]
If you have a standard WeeWX install then your `PYTHONPATH` is wrong, the command should be:
```
$ sudo PYTHONPATH=/home/weewx/bin python3 -m user.gw1000 --test-driver
```
I did a quick search of the GW1000 driver and wiki and could not find the `PYTHONPATH` value you have used, if you found it in the driver or wiki could you let me know where it is and I will fix it.

**Comment by Rayvenhaus** [comment]
That was it. I must have made a typo when transferring the command to my notes. Sorry for the erroneous bug report.
