### ISSUE TITLE
Ver 0.6.0 not found to download 

### ISSUE THREAD

**Issue by nady2804** [gjr80/weewx-gw1000#62]
i can't find the latest version 0.6.0 ??
i use the GW2000 Gateway and now i installed the 0.5.0 version

**Comment by mafen** [comment]
6.0 is not out yet

**Comment by nady2804** [comment]
ok ,because the first page instruction is already for the 0.6.0. version.

Thx Manfred



Am Do., 18. Mai 2023 um 19:18 Uhr schrieb Markus F ***@***.***

**Comment by mafen** [comment]
you can do it if you download the repo and install it that way, it is possible but it would be WIP

**Comment by nady2804** [comment]
Thx.

Am Do., 18. Mai 2023 um 19:24 Uhr schrieb Markus F ***@***.***

**Comment by gjr80** [comment]
I wasn't aware the readme contained v0.6.0 details. I have reverted it to v0.5.0b5.

The v0.6.0b1 code is done, I just have a few other things to fix before release. Unfortunately other things have taken priority, the best I can say at present is v0.6.0 will be released 'soon'.
