### ISSUE TITLE
Driver was not loading after system reboot

### ISSUE THREAD

**Issue by lemuba** [gjr80/weewx-gw1000#7]
I installed rsyslog and was promted to reboot my machine for this.
After the reboot weewx was loading, but not the driver.

To fix the problem I had to:
sudo /etc/init.d/weewx restart

user.log:

Jul 26 11:27:54 DietPi blkmapd[265]: open pipe file /run/rpc_pipefs/nfs/blocklayout failed: No such file or directory
Jul 26 11:28:11 DietPi weewx[379] INFO __main__: Initializing weewx version 4.1.1
Jul 26 11:28:11 DietPi weewx[379] INFO __main__: Using Python 3.5.3 (default, Jul  9 2020, 13:00:10) #012[GCC 6.3.0 20170516]
Jul 26 11:28:12 DietPi weewx[379] INFO __main__: Platform Linux-4.9.0-12-amd64-x86_64-with-debian-9.13
Jul 26 11:28:12 DietPi weewx[379] INFO __main__: Locale is 'de_DE.UTF-8'
Jul 26 11:28:12 DietPi weewx[379] INFO __main__: PID file is /var/run/weewx.pid
Jul 26 11:28:12 DietPi weewx[849] INFO __main__: Using configuration file /home/weewx/weewx.conf
Jul 26 11:28:12 DietPi weewx[849] INFO __main__: Debug is 0
Jul 26 11:28:12 DietPi weewx[849] INFO weewx.engine: Loading station type GW1000 (user.gw1000)
Jul 26 11:28:14 DietPi weewx[849] ERROR weewx.engine: Import of driver failed: local variable 'disc_ip' referenced before assignment (<class 'UnboundLocalError'>)
Jul 26 11:28:16 DietPi weewx[849] CRITICAL weewx.engine:     ****  Traceback (most recent call last):
Jul 26 11:28:16 DietPi weewx[849] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/weewx/engine.py", line 103, in setupStation
Jul 26 11:28:16 DietPi weewx[849] CRITICAL weewx.engine:     ****      self.console = loader_function(config_dict, self)
Jul 26 11:28:16 DietPi weewx[849] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 832, in loader
Jul 26 11:28:16 DietPi weewx[849] CRITICAL weewx.engine:     ****      return Gw1000Driver(**config_dict[DRIVER_NAME])
Jul 26 11:28:16 DietPi weewx[849] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 917, in __init__
Jul 26 11:28:16 DietPi weewx[849] CRITICAL weewx.engine:     ****      super(Gw1000Driver, self).__init__(**stn_dict)
Jul 26 11:28:16 DietPi weewx[849] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 553, in __init__
Jul 26 11:28:16 DietPi weewx[849] CRITICAL weewx.engine:     ****      retry_wait=self.retry_wait)
Jul 26 11:28:16 DietPi weewx[849] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 1103, in __init__
Jul 26 11:28:16 DietPi weewx[849] CRITICAL weewx.engine:     ****      retry_wait=retry_wait)
Jul 26 11:28:16 DietPi weewx[849] CRITICAL weewx.engine:     ****    File "/home/weewx/bin/user/gw1000.py", line 1395, in __init__
Jul 26 11:28:16 DietPi weewx[849] CRITICAL weewx.engine:     ****      ip_address = disc_ip.encode() if ip_address is None else ip_address.encode()
Jul 26 11:28:16 DietPi weewx[849] CRITICAL weewx.engine:     ****  UnboundLocalError: local variable 'disc_ip' referenced before assignment
Jul 26 11:28:16 DietPi weewx[849] CRITICAL __main__: Unable to load driver: local variable 'disc_ip' referenced before assignment
Jul 26 11:28:16 DietPi weewx[849] CRITICAL __main__:     ****  Exiting...
Jul 26 11:29:11 DietPi org.kde.KScreen[1331]: kscreen.xrandr: Connected output 64 to CRTC 63
Jul 26 11:29:11 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: Detected XRandR 1.5
Jul 26 11:29:11 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: Event Base:  89
Jul 26 11:29:11 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: Event Error:  147
Jul 26 11:29:12 DietPi org.a11y.atspi.Registry[1508]: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: XRandR::setConfig
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: Requested screen size is QSize(1280, 960)
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: Needed CRTCs:  1
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: Actions to perform:
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011Primary Output: false
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011Change Screen Size: true
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011#011Old: QSize(1024, 768)
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011#011Intermediate: QSize(1280, 960)
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011#011New: QSize(1280, 960)
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011Disable outputs: false
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011Change outputs: true
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011#011 (64)
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011Enable outputs: false
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: RRSetScreenSize
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011DPI: 96.0946
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011Size: QSize(1280, 960)
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011SizeMM: QSize(338, 253)
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: RRSetCrtcConfig (change output)
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011Output: 64 ( "VGA-1" )
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011CRTC: 63
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011Pos: QPoint(0,0)
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011Mode: 68 KScreen::Mode(Id: "68" , Size: QSize(1280, 960) )
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011Rotation: 1
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011Result:  0
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: XRandROutput 64 update
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011m_connected: 0
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011m_crtc XRandRCrtc(0x564dd65ca610)
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011CRTC: 63
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011MODE: 68
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011Connection: 0
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: #011Primary: true
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: XRandR::setConfig done!
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: RRScreenChangeNotify
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011Window: 14680068
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011Root: 620
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011Rotation:  "Rotate_0"
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011Size ID: 2
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011Size:  1280 960
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011SizeMM:  338 253
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: RRNotify_CrtcChange
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011CRTC:  63
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011Mode:  68
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011Rotation:  "Rotate_0"
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011Geometry:  0 0 1280 960
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: RRScreenChangeNotify
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011Window: 14680068
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011Root: 620
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011Rotation:  "Rotate_0"
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011Size ID: 2
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011Size:  1280 960
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011SizeMM:  338 253
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: RRNotify_CrtcChange
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011CRTC:  63
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011Mode:  68
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011Rotation:  "Rotate_0"
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xcb.helper: #011Geometry:  0 0 1280 960
Jul 26 11:29:12 DietPi org.kde.KScreen[1331]: kscreen.xrandr: Emitting configChanged()
Jul 26 11:29:21 DietPi org.gtk.vfs.AfcVolumeMonitor[1331]: Volume monitor alive
Jul 26 11:31:26 DietPi org.a11y.atspi.Registry[2803]: SpiRegistry daemon is running with well-known name - org.a11y.atspi.Registry
Jul 26 11:31:27 DietPi org.kde.KScreen[2752]: kscreen.xrandr: Connected output 60 to CRTC 59
Jul 26 11:31:27 DietPi org.kde.KScreen[2752]: kscreen.xcb.helper: Detected XRandR 1.5
Jul 26 11:31:27 DietPi org.kde.KScreen[2752]: kscreen.xcb.helper: Event Base:  92
Jul 26 11:31:27 DietPi org.kde.KScreen[2752]: kscreen.xcb.helper: Event Error:  147
Jul 26 11:31:27 DietPi org.kde.KScreen[2752]: kscreen.xrandr: XRandR::setConfig
Jul 26 11:31:27 DietPi org.kde.KScreen[2752]: kscreen.xrandr: Requested screen size is QSize(1024, 768)
Jul 26 11:31:27 DietPi org.kde.KScreen[2752]: kscreen.xrandr: Needed CRTCs:  1
Jul 26 11:31:27 DietPi org.kde.KScreen[2752]: kscreen.xrandr: Actions to perform:
Jul 26 11:31:27 DietPi org.kde.KScreen[2752]: kscreen.xrandr: #011Primary Output: false
Jul 26 11:31:27 DietPi org.kde.KScreen[2752]: kscreen.xrandr: #011Change Screen Size: false
Jul 26 11:31:27 DietPi org.kde.KScreen[2752]: kscreen.xrandr: #011Disable outputs: false
Jul 26 11:31:27 DietPi org.kde.KScreen[2752]: kscreen.xrandr: #011Change outputs: false
Jul 26 11:31:27 DietPi org.kde.KScreen[2752]: kscreen.xrandr: #011Enable outputs: false
Jul 26 11:31:27 DietPi org.kde.KScreen[2752]: kscreen.xrandr: XRandR::setConfig done!
Jul 26 11:31:27 DietPi org.gtk.vfs.AfcVolumeMonitor[2752]: Volume monitor alive
Jul 26 11:34:45 DietPi weewx[4045] DEBUG gw1000: __main__: Sending broadcast packet 'FF FF 12 03 15' to '255.255.255.255:46000'
Jul 26 11:34:45 DietPi weewx[4045] DEBUG gw1000: __main__: Received broadcast response 'FF FF 12 00 21 A4 CF 12 B4 FB 23 C0 A8 0C BD AF C8 10 47 57 31 30 30 30 41 2D 57 49 46 49 46 42 32 33 0A'
Jul 26 11:34:47 DietPi weewx[4045] INFO gw1000: __main__: GW1000 was found at 192.168.12.189:45000
Jul 26 11:34:47 DietPi weewx[4045] DEBUG gw1000: __main__: Sending packet 'FF FF 27 03 2A' to '192.168.12.189:45000'
Jul 26 11:34:47 DietPi weewx[4045] DEBUG gw1000: __main__: Received response 'FF FF 27 00 5D 01 01 0C 06 34 08 27 3B 09 27 3B 02 00 B8 07 5E 0A 01 30 0B 00 09 0C 00 0A 15 00 04 04 16 16 02 2E 17 02 4C 0F 00 00 00 03 FF FF 00 FF FF FF FF FF FF FF FF 62 00 00 00 00 61 FF FF FF FF 60 FF 19 00 2E 0E 00 00 10 00 12 11 00 12 12 00 00 03 58 13 00 00 07 0D 0D 00 0A 6E'
Jul 26 11:34:47 DietPi weewx[4045] DEBUG gw1000: __main__: sensor data is '01 01 0C 06 34 08 27 3B 09 27 3B 02 00 B8 07 5E 0A 01 30 0B 00 09 0C 00 0A 15 00 04 04 16 16 02 2E 17 02 4C 0F 00 00 00 03 FF FF 00 FF FF FF FF FF FF FF FF 62 00 00 00 00 61 FF FF FF FF 60 FF 19 00 2E 0E 00 00 10 00 12 11 00 12 12 00 00 03 58 13 00 00 07 0D 0D 00 0A'
Jul 26 11:34:47 DietPi weewx[4045] DEBUG gw1000: __main__: Parsed data: {'wh31_ch6_batt': 0, 'wh41_ch3_batt': None, 'rainyear': 180.5, 'outtemp': 18.4, 'wh51_ch2_batt': 0, 'light': 26319.0, 'wh51_ch14_batt': 0, 'rainevent': 1.0, 'wh51_ch5_batt': 0, 'wh24_batt': 0, 'relbarometer': 1004.3, 'lightningdettime': None, 'wh51_ch7_batt': 0, 'wh31_ch2_batt': 0, 'wh51_ch4_batt': 0, 'wh51_ch10_batt': 0, 'ws80_batt': 5.1000000000000005, 'wh41_ch1_batt': None, 'wh55_ch4_batt': None, 'wh31_ch8_batt': 0, 'windspeed': 0.9, 'absbarometer': 1004.3, 'uv': 55.8, 'wh51_ch13_batt': 0, 'datetime': 1595756087, 'wh57_batt': 3, 'lightningdist': None, 'wh55_ch2_batt': None, 'wh26_batt': 0, 'daymaxwind': 4.6, 'wh51_ch11_batt': 0, 'winddir': 30.4, 'wh31_ch7_batt': 0, 'outhumid': 94, 'wh51_ch3_batt': 0, 'lightningcount': 0, 'wh41_ch4_batt': None, 'ws68_batt': 5.1000000000000005, 'wh51_ch9_batt': 0, 'wh40_batt': 0, 'intemp': 26.8, 'wh55_ch1_batt': None, 'uvi': 2, 'wh41_ch2_batt': None, 'inhumid': 52, 'wh51_ch8_batt': 0, 'rainday': 1.8, 'wh51_ch1_batt': 0, 'wh31_ch4_batt': 0, 'wh51_ch15_batt': 0, 'rainrate': 0.0, 'wh31_ch1_batt': 0, 'rainmonth': 85.6, 'wh25_batt': 0, 'wh31_ch3_batt': 0, 'wh51_ch6_batt': 0, 'gustspeed': 1.0, 'wh51_ch16_batt': 0, 'wh55_ch3_batt': None, 'rainweek': 1.8, 'wh31_ch5_batt': 0, 'wh51_ch12_batt': 0}
Jul 26 11:34:47 DietPi weewx[4045] DEBUG gw1000: __main__: Sending packet 'FF FF 3A 03 3D' to '192.168.12.189:45000'
Jul 26 11:34:47 DietPi weewx[4045] DEBUG gw1000: __main__: Received response 'FF FF 3A D5 00 00 00 00 79 00 04 01 FF FF FF FF FF 00 02 FF FF FF FF FF 00 03 FF FF FF FF 00 00 05 FF FF FF FF 00 00 06 FF FF FF FF 00 00 07 FF FF FF FF 00 00 08 FF FF FF FF 00 00 09 FF FF FF FF 00 00 0A FF FF FF FF 00 00 0B FF FF FF FF 00 00 0C FF FF FF FF 00 00 0D FF FF FF FF 00 00 0E FF FF FF FF 00 00 0F FF FF FF FF 00 00 10 FF FF FF FF 00 00 11 FF FF FF FF 00 00 12 FF FF FF FF 00 00 13 FF FF FF FF 00 00 14 FF FF FF FF 00 00 15 FF FF FF FF 00 00 16 FF FF FF FF 0F 00 17 FF FF FF FF 0F 00 18 FF FF FF FF 0F 00 19 FF FF FF FF 0F 00 1A 00 00 D0 3E 03 04 1B FF FF FF FF FF 00 1C FF FF FF FF FF 00 1D FF FF FF FF FF 00 1E FF FF FF FF FF 00 34'
Jul 26 11:34:47 DietPi weewx[4045] DEBUG gw1000: __main__: Filtered parsed data: {'windspeed': 0.9, 'outtemp': 18.4, 'gustspeed': 1.0, 'light': 26319.0, 'rainevent': 1.0, 'inhumid': 52, 'relbarometer': 1004.3, 'lightningdettime': None, 'absbarometer': 1004.3, 'rainyear': 180.5, 'uv': 55.8, 'datetime': 1595756087, 'wh57_batt': 3, 'lightningdist': None, 'daymaxwind': 4.6, 'winddir': 30.4, 'outhumid': 94, 'lightningcount': 0, 'intemp': 26.8, 'uvi': 2, 'rainrate': 0.0, 'rainday': 1.8, 'rainmonth': 85.6, 'rainweek': 1.8}
Jul 26 11:34:55 DietPi weewx[4240] DEBUG gw1000: __main__: Sending broadcast packet 'FF FF 12 03 15' to '255.255.255.255:46000'
Jul 26 11:34:55 DietPi weewx[4240] DEBUG gw1000: __main__: Received broadcast response 'FF FF 12 00 21 A4 CF 12 B4 FB 23 C0 A8 0C BD AF C8 10 47 57 31 30 30 30 41 2D 57 49 46 49 46 42 32 33 0A'
Jul 26 11:34:57 DietPi weewx[4240] INFO gw1000: __main__: GW1000 was found at 192.168.12.189:45000
Jul 26 11:34:57 DietPi weewx[4240] DEBUG gw1000: __main__: Sending packet 'FF FF 27 03 2A' to '192.168.12.189:45000'
Jul 26 11:34:57 DietPi weewx[4240] DEBUG gw1000: __main__: Received response 'FF FF 27 00 5D 01 01 0C 06 34 08 27 3B 09 27 3B 02 00 B8 07 5E 0A 01 30 0B 00 09 0C 00 0A 15 00 04 04 16 16 02 2E 17 02 4C 0F 00 00 00 03 FF FF 00 FF FF FF FF FF FF FF FF 62 00 00 00 00 61 FF FF FF FF 60 FF 19 00 2E 0E 00 00 10 00 12 11 00 12 12 00 00 03 58 13 00 00 07 0D 0D 00 0A 6E'
Jul 26 11:34:57 DietPi weewx[4240] DEBUG gw1000: __main__: sensor data is '01 01 0C 06 34 08 27 3B 09 27 3B 02 00 B8 07 5E 0A 01 30 0B 00 09 0C 00 0A 15 00 04 04 16 16 02 2E 17 02 4C 0F 00 00 00 03 FF FF 00 FF FF FF FF FF FF FF FF 62 00 00 00 00 61 FF FF FF FF 60 FF 19 00 2E 0E 00 00 10 00 12 11 00 12 12 00 00 03 58 13 00 00 07 0D 0D 00 0A'
Jul 26 11:34:57 DietPi weewx[4240] DEBUG gw1000: __main__: Parsed data: {'absbarometer': 1004.3, 'ws80_batt': 5.1000000000000005, 'wh51_ch9_batt': 0, 'wh51_ch14_batt': 0, 'wh31_ch5_batt': 0, 'rainrate': 0.0, 'wh25_batt': 0, 'winddir': 30.4, 'rainday': 1.8, 'wh51_ch2_batt': 0, 'wh55_ch4_batt': None, 'uvi': 2, 'wh31_ch3_batt': 0, 'lightningcount': 0, 'rainmonth': 85.6, 'wh51_ch5_batt': 0, 'wh31_ch4_batt': 0, 'wh57_batt': 3, 'wh24_batt': 0, 'wh51_ch10_batt': 0, 'rainweek': 1.8, 'outtemp': 18.4, 'wh51_ch7_batt': 0, 'gustspeed': 1.0, 'wh31_ch2_batt': 0, 'wh41_ch3_batt': None, 'lightningdist': None, 'wh51_ch6_batt': 0, 'wh55_ch2_batt': None, 'relbarometer': 1004.3, 'windspeed': 0.9, 'uv': 55.8, 'light': 26319.0, 'wh51_ch16_batt': 0, 'outhumid': 94, 'wh51_ch1_batt': 0, 'datetime': 1595756097, 'wh26_batt': 0, 'intemp': 26.8, 'wh31_ch7_batt': 0, 'wh51_ch12_batt': 0, 'wh51_ch13_batt': 0, 'wh31_ch1_batt': 0, 'wh31_ch6_batt': 0, 'wh51_ch15_batt': 0, 'inhumid': 52, 'wh40_batt': 0, 'wh31_ch8_batt': 0, 'wh41_ch4_batt': None, 'rainyear': 180.5, 'wh51_ch3_batt': 0, 'lightningdettime': None, 'wh51_ch8_batt': 0, 'wh55_ch3_batt': None, 'wh41_ch1_batt': None, 'wh51_ch11_batt': 0, 'ws68_batt': 5.1000000000000005, 'wh55_ch1_batt': None, 'rainevent': 1.0, 'wh41_ch2_batt': None, 'wh51_ch4_batt': 0, 'daymaxwind': 4.6}
Jul 26 11:34:57 DietPi weewx[4240] DEBUG gw1000: __main__: Sending packet 'FF FF 3A 03 3D' to '192.168.12.189:45000'
Jul 26 11:34:57 DietPi weewx[4240] DEBUG gw1000: __main__: Received response 'FF FF 3A D5 00 00 00 00 79 00 04 01 FF FF FF FF FF 00 02 FF FF FF FF FF 00 03 FF FF FF FF 00 00 05 FF FF FF FF 00 00 06 FF FF FF FF 00 00 07 FF FF FF FF 00 00 08 FF FF FF FF 00 00 09 FF FF FF FF 00 00 0A FF FF FF FF 00 00 0B FF FF FF FF 00 00 0C FF FF FF FF 00 00 0D FF FF FF FF 00 00 0E FF FF FF FF 00 00 0F FF FF FF FF 00 00 10 FF FF FF FF 00 00 11 FF FF FF FF 00 00 12 FF FF FF FF 00 00 13 FF FF FF FF 00 00 14 FF FF FF FF 00 00 15 FF FF FF FF 00 00 16 FF FF FF FF 0F 00 17 FF FF FF FF 0F 00 18 FF FF FF FF 0F 00 19 FF FF FF FF 0F 00 1A 00 00 D0 3E 03 04 1B FF FF FF FF FF 00 1C FF FF FF FF FF 00 1D FF FF FF FF FF 00 1E FF FF FF FF FF 00 34'
Jul 26 11:34:57 DietPi weewx[4240] DEBUG gw1000: __main__: Filtered parsed data: {'absbarometer': 1004.3, 'uv': 55.8, 'inhumid': 52, 'winddir': 30.4, 'rainday': 1.8, 'rainrate': 0.0, 'lightningcount': 0, 'rainmonth': 85.6, 'rainweek': 1.8, 'wh57_batt': 3, 'outtemp': 18.4, 'gustspeed': 1.0, 'relbarometer': 1004.3, 'windspeed': 0.9, 'light': 26319.0, 'outhumid': 94, 'intemp': 26.8, 'daymaxwind': 4.6, 'datetime': 1595756097, 'uvi': 2, 'rainyear': 180.5, 'lightningdettime': None, 'lightningdist': None, 'rainevent': 1.0}
Jul 26 11:42:01 DietPi weewx[7355] INFO __main__: Initializing weewx version 4.1.1
Jul 26 11:42:01 DietPi weewx[7355] INFO __main__: Using Python 3.5.3 (default, Jul  9 2020, 13:00:10) #012[GCC 6.3.0 20170516]
Jul 26 11:42:01 DietPi weewx[7355] INFO __main__: Platform Linux-4.9.0-12-amd64-x86_64-with-debian-9.13
Jul 26 11:42:01 DietPi weewx[7355] INFO __main__: Locale is 'de_DE.UTF-8'
Jul 26 11:42:01 DietPi weewx[7355] INFO __main__: PID file is /var/run/weewx.pid
Jul 26 11:42:01 DietPi weewx[7359] INFO __main__: Using configuration file /home/weewx/weewx.conf
Jul 26 11:42:01 DietPi weewx[7359] INFO __main__: Debug is 0
Jul 26 11:42:01 DietPi weewx[7359] INFO weewx.engine: Loading station type GW1000 (user.gw1000)
Jul 26 11:42:03 DietPi weewx[7359] INFO gw1000: user.gw1000: GW1000 was found at 192.168.12.189:45000
Jul 26 11:42:03 DietPi weewx[7359] INFO gw1000: user.gw1000: field map is {'24havpm251': '24havpm251', '24havpm252': '24havpm252', '24havpm253': '24havpm253', '24havpm254': '24havpm254', 'UV': 'uvi', 'barometer': 'relbarometer', 'dateTime': 'datetime', 'daymaxwind': 'daymaxwind', 'dewpoint': 'dewpoint', 'extraHumid1': 'humid1', 'extraHumid2': 'humid2', 'extraHumid3': 'humid3', 'extraHumid4': 'humid4', 'extraHumid5': 'humid5', 'extraHumid6': 'humid6', 'extraHumid7': 'humid7', 'extraHumid8': 'humid8', 'extraTemp1': 'temp1', 'extraTemp2': 'temp2', 'extraTemp3': 'temp3', 'extraTemp4': 'temp4', 'extraTemp5': 'temp5', 'extraTemp6': 'temp6', 'extraTemp7': 'temp7', 'extraTemp8': 'temp8', 'heatindex': 'heatindex', 'inHumidity': 'inhumid', 'inTemp': 'intemp', 'leak1': 'leak1', 'leak2': 'leak2', 'leak3': 'leak3', 'leak4': 'leak4', 'lightning_distance': 'lightningdist', 'lightning_last_det_time': 'lightningdettime', 'lightning_strike_count': 'lightning_strike_count', 'luminosity': 'light', 'outHumidity': 'outhumid', 'outTemp': 'outtemp', 'pm2_5': 'pm251', 'pm2_52': 'pm252', 'pm2_53': 'pm253', 'pm2_54': 'pm254', 'pressure': 'absbarometer', 'rainRate': 'rainrate', 'rainday': 'rainday', 'rainevent': 'rainevent', 'rainhour': 'rainhour', 'rainmonth': 'rainmonth', 'raintotals': 'raintotals', 'rainweek': 'rainweek', 'rainyear': 'rainyear', 'soilMoist1': 'soilmoist1', 'soilMoist2': 'soilmoist2', 'soilMoist3': 'soilmoist3', 'soilMoist4': 'soilmoist4', 'soilMoist5': 'soilmoist5', 'soilMoist6': 'soilmoist6', 'soilMoist7': 'soilmoist7', 'soilMoist8': 'soilmoist8', 'soilMoist9': 'soilmoist9', 'soilMoist10': 'soilmoist10', 'soilMoist11': 'soilmoist11', 'soilMoist12': 'soilmoist12', 'soilMoist13': 'soilmoist13', 'soilMoist14': 'soilmoist14', 'soilMoist15': 'soilmoist15', 'soilMoist16': 'soilmoist16', 'soilTemp1': 'soiltemp1', 'soilTemp2': 'soiltemp2', 'soilTemp3': 'soiltemp3', 'soilTemp4': 'soiltemp4', 'soilTemp5': 'soiltemp5', 'soilTemp6': 'soiltemp6', 'soilTemp7': 'soiltemp7', 'soilTemp8': 'soiltemp8', 'soilTemp9': 'soiltemp9', 'soilTemp10': 'soiltemp10', 'soilTemp11': 'soiltemp11', 'soilTemp12': 'soiltemp12', 'soilTemp13': 'soiltemp13', 'soilTemp14': 'soiltemp14', 'soilTemp15': 'soiltemp15', 'soilTemp16': 'soiltemp16', 'uvRadiation': 'uv', 'windDir': 'winddir', 'windGust': 'gustspeed', 'windSpeed': 'windspeed', 'windchill': 'windchill'}
Jul 26 11:42:03 DietPi weewx[7359] INFO gw1000: user.gw1000: driver version is 0.1.0b5
Jul 26 11:42:03 DietPi weewx[7359] INFO gw1000: user.gw1000: GW1000 IP address not specified, attempting to discover GW1000...
Jul 26 11:42:03 DietPi weewx[7359] INFO gw1000: user.gw1000: GW1000 address is 192.168.12.189:45000
Jul 26 11:42:03 DietPi weewx[7359] INFO gw1000: user.gw1000: poll interval is 10 seconds
Jul 26 11:42:03 DietPi weewx[7359] INFO weewx.engine: StdConvert target unit is 0x1
Jul 26 11:42:03 DietPi weewx[7359] INFO weewx.wxservices: The following values will be calculated: pressure=prefer_hardware, altimeter=prefer_hardware, appTemp=prefer_hardware, barometer=prefer_hardware, beaufort=prefer_hardware, cloudbase=prefer_hardware, dewpoint=prefer_hardware, ET=prefer_hardware, heatindex=prefer_hardware, humidex=prefer_hardware, inDewpoint=prefer_hardware, maxSolarRad=prefer_hardware, rainRate=prefer_hardware, windchill=prefer_hardware, windrun=prefer_hardware
Jul 26 11:42:03 DietPi weewx[7359] INFO weewx.wxservices: The following algorithms will be used for calculations: altimeter=aaASOS, maxSolarRad=RS
Jul 26 11:42:03 DietPi weewx[7359] INFO weewx.engine: Archive will use data binding wx_binding
Jul 26 11:42:03 DietPi weewx[7359] INFO weewx.engine: Record generation will be attempted in 'software'
Jul 26 11:42:03 DietPi weewx[7359] INFO weewx.engine: Using archive interval of 300 seconds (software record generation)
Jul 26 11:42:03 DietPi weewx[7359] INFO weewx.restx: StationRegistry: Registration not requested.
Jul 26 11:42:03 DietPi weewx[7359] INFO weewx.restx: Wunderground: Posting not enabled.
Jul 26 11:42:03 DietPi weewx[7359] INFO weewx.restx: PWSWeather: Data for station FITZBEK will be posted
Jul 26 11:42:03 DietPi weewx[7359] INFO weewx.restx: CWOP: Posting not enabled.
Jul 26 11:42:03 DietPi weewx[7359] INFO weewx.restx: WOW: Posting not enabled.
Jul 26 11:42:03 DietPi weewx[7359] INFO weewx.restx: AWEKAS: Posting not enabled.
Jul 26 11:42:03 DietPi weewx[7359] INFO user.mqtt: service version is 0.23
Jul 26 11:42:03 DietPi weewx[7359] INFO user.mqtt: binding to ['archive', 'loop']
Jul 26 11:42:03 DietPi weewx[7359] INFO user.mqtt: topic is weather
Jul 26 11:42:03 DietPi weewx[7359] INFO user.mqtt: desired unit system is METRIC
Jul 26 11:42:03 DietPi weewx[7359] INFO user.mqtt: data will be uploaded to mqtt://192.168.12.127:9002/
Jul 26 11:42:03 DietPi weewx[7359] INFO __main__: Starting up weewx version 4.1.1
Jul 26 11:42:03 DietPi weewx[7359] INFO weewx.engine: Using binding 'wx_binding' to database 'weewx.sdb'
Jul 26 11:42:03 DietPi weewx[7359] INFO weewx.manager: Starting backfill of daily summaries
Jul 26 11:42:03 DietPi weewx[7359] INFO weewx.engine: Starting main packet loop.
Jul 26 11:42:03 DietPi weewx[7359] INFO gw1000: user.gw1000: using 'rainyear' for rain total
Jul 26 11:42:03 DietPi weewx[7359] INFO gw1000: user.gw1000: skipping rain measurement of 180.5: no last rain
Jul 26 11:42:03 DietPi weewx[7359] INFO gw1000: user.gw1000: skipping lightning count of 0: no last count

**Comment by gjr80** [comment]
It appears that the driver received no replies to a broadcast message looking for any GW1000s. A logic error in the code then resulted in the error. I have hardened up the startup code to have a default of three attempts with a default of five seconds between attempts to locate a GW1000. If no GW1000 is found after this the driver fails hard with a suitable message.

Will be included in b6.
