### ISSUE TITLE
V.0.6.0 driver mode: ‘field_map_extensions’ is not being “used”

### ISSUE THREAD

**Issue by bellrichm** [gjr80/weewx-gw1000#72]
I noticed that my field mapping via `field_map_extensions` was not happening with v0.6.0. In `construct_field_map` the `gw_config` was empty.
I changed line 1179 from `def construct_field_map(self, **gw_config):` to `def construct_field_map(gw_config):`and the mapping is working.

**Comment by gjr80** [comment]
Thanks Rich, fixed at v0.6.1
