### ISSUE TITLE
Rain gauge information does not translate for WeeWX and beyond

### ISSUE THREAD

**Issue by svenjr** [gjr80/weewx-gw1000#76]
Information shows up via EcoWitt (see below)

![Screenshot 2024-04-12 at 14 27 17](https://github.com/gjr80/weewx-gw1000/assets/36718299/eb3c4204-9cbe-479d-ad60-c7a6d9f2b3dd)

but this data does not track through to WeeWx
![Screenshot 2024-04-12 at 14 27 57](https://github.com/gjr80/weewx-gw1000/assets/36718299/d0835fe2-4a3e-4a58-bdf6-3c13b556291e)

**Comment by gjr80** [comment]
If you have a piezo rain gauge you need to configure the driver and/or WeeWX to use the rain data from the piezo rain gauge. The easiest way to do this is to alter the driver field map to map the piezo rain data to the standard WeeWX rain fields. Did you do this?

Refer to the _[I have an Ecowitt piezo rain gauge, how do I get my rainfall data into WeeWX?](https://github.com/gjr80/weewx-gw1000/wiki/Frequently-asked-questions#sensors)_ FAQ in the driver wiki, it should help you.

**Comment by gjr80** [comment]
Closing due to no response. Can be re-opened if required.
